/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jte.repro;

import gg.jte.ContentType;
import gg.jte.TemplateEngine;
import gg.jte.TemplateOutput;
import gg.jte.output.StringOutput;

public class Library {
    public String render(MyModel model) {
        var output = new StringOutput();
        var templateEngine = TemplateEngine.createPrecompiled(ContentType.Plain);
        templateEngine.render("sometemplate", model, output);

        return output.toString();
    }
}
