/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jte.repro;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertEquals(classUnderTest.render(new MyModel()), "Some Text");
    }
}
